# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rushuffle <- function(x, k, n) {
    .Call(`_uShuffleR_rushuffle`, x, k, n)
}

